name: "Custom action"
  
description: "Greet someone"   
inputs: 
  name_input:
    description: "the name"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: "Great the user"
      run: echo "Hello ${{ inputs.name_input }}."
      shell: bash
      
